name: Context

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: ENV
        run: |
          Write-Host "ModulePath: '$ENV:PSModulePath'"
          Write-Host "GITHUB_EVENT_PATH: '$ENV:GITHUB_EVENT_PATH'"
          dir env:


      - name: mask
        run: |
          Write-Host -nonewline "This is a test"
          Write-Host "`r::add-mask::Freddy"

      - name: print
        run: |
          Write-Host "Freddy Kristiansen"

      - name: event
        run: |
          Get-Content "$ENV:GITHUB_EVENT_PATH" -encoding UTF8

      - name: Echo on private
        run: echo "I am private"
        if: ${{github.event.repository.private}}
