name: Dir

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: info
        run: |
          Write-Host "::notice::This is a notice"
          Write-Host "::warning::This is a warning"
          
      - name: GCI
        run: |
          Set-location "c:\"
          Get-ChildItem
          Add-Content -Path $env:GITHUB_ENV -Value "TESTENV=FREDDY"

      - name: GCI2
        run: |
          Write-Host "ENVVAR $ENV:TESTENV"

      - name: Get-InstalledModule
        run: |
          Get-InstalledModule

      - name: Get-Module
        run: |
          Get-Module

      - name: Get-Module-ListAvailable
        run: |
          (Get-Module -Name 'AzureRM.KeyVault' -listAvailable).ExportedCommands
          Write-Host "-------"
          (Get-Module -Name 'AzureRM.Profile' -listAvailable).ExportedCommands

      - name: ReadFromKeyVault
        run: |
          $azureCredentials = '${{ Secrets.Azure_Credentials }}' | ConvertFrom-Json
          $azureCredentials.KeyVaultName
          Get-Module -Name 'AzureRM.KeyVault' -listAvailable | Import-Module -WarningAction SilentlyContinue
          Get-Module -Name 'AzureRM.Profile' -listAvailable | Import-Module -WarningAction SilentlyContinue
          Disable-AzureRmDataCollection -WarningAction SilentlyContinue
          $credential = New-Object PSCredential -argumentList $azureCredentials.clientId, (ConvertTo-SecureString $azureCredentials.clientSecret -AsPlainText -Force)
          Add-AzureRmAccount -ServicePrincipal -Tenant $azureCredentials.tenantId -Credential $credential -WarningAction SilentlyContinue | Out-Null
          Set-AzureRmContext -SubscriptionId $azureCredentials.subscriptionId -Tenant $azureCredentials.tenantId -WarningAction SilentlyContinue | Out-Null
          $keyVaultSecret = Get-AzureKeyVaultSecret -VaultName $azureCredentials.keyVaultName -Name 'Password'
          if ($keyVaultSecret) {
            $value = [Runtime.InteropServices.Marshal]::PtrToStringBSTR(([Runtime.InteropServices.Marshal]::SecureStringToBSTR($keyVaultSecret.SecretValue)))
            Write-Host "The password is $value"
          }
          else {
            Write-Host "No password secret available"
          }
         
