name: Secrets

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read Settings
        run: |
          # This servers as an example of Read Settings, leaving a secret mapping for the ReadSecrets
          $settings = @{ "TestSecretSecretName" = "NYTEST" } | ConvertTo-Json -compress
          Add-Content -Path $env:GITHUB_ENV -Value "settings=$settings"

      - name: Get Secret Specification
        id: GetSecretsSpec
        env:
          Secrets: ghTokenWorkflow,TestSecret,SomeTest,OtherSecret
        run: |
          # Create a number of outputs named S0, S1, S2, etc. for each secret, holding the actual GitHub Secret name to look for
          # Create a json format string for the secrets, to be used in the next step
          $settings = $env:settings | ConvertFrom-Json
          $formatArr = @()
          $cnt = 0
          foreach($secret in $env:Secrets.Split(',')) {
            $secretName = $secret
            if ($settings.PSObject.Properties.Name -eq "$($secret)SecretName") {
              $secretName = $settings."$($secret)SecretName"
            }
            $formatArr += @("""$Secret"":{$cnt}")
            Add-Content $ENV:GITHUB_ENV "S$cnt=$secretName"
            Write-Host "S$cnt=$secretName"
            $cnt++
          }
          Write-Host "formatStr={{$($formatArr -join ',')}}"
          Add-Content $ENV:GITHUB_OUTPUT "formatStr={{$($formatArr -join ',')}}"
          if ($cnt -gt 16) {
            throw "Too many secrets"
          }

      - name: ReadSecretFromGitHub
        id: ReadSecretsFromGitHub
        env:
          SECRETS_JSON: ${{ format(steps.GetSecretsSpec.outputs.formatStr,toJSON(secrets[env.S0]),toJSON(secrets[env.S1]),toJSON(secrets[env.S2]),toJSON(secrets[env.S3]),toJSON(secrets[env.S4]),toJSON(secrets[env.S5]),toJSON(secrets[env.S6]),toJSON(secrets[env.S7]),toJSON(secrets[env.S8]),toJSON(secrets[env.S9]),toJSON(secrets[env.S10]),toJSON(secrets[env.S11]),toJSON(secrets[env.S12]),toJSON(secrets[env.S13]),toJSON(secrets[env.S14]),toJSON(secrets[env.S15])) }}
        run: |
          # Add secrets as Json to GitHub output
          Add-Content -encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "Secrets=$ENV:SECRETS_JSON"

      - name: ReadSecret
        id: ReadSecrets
        run: |
          # Call into action to retrieve the missing secrets from Azure Key Vault if avaialable
          # Ensure encoding etc. is done correctly
