name: Secrets

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

env:
  SN: S2
  SX: S3

jobs:
  update:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: GetSecret1
        id: getsecrets1
        env:
          FORMATSTR: '''{{"S1":{0},"${{env.SX}}":{1},"${{env.SN}}":{2}}}'''
          SECRETS_JSON: ${{ format(env.FORMATSTR,toJSON(secrets.S1),toJSON(secrets[env.SX]),toJSON(secrets[env.SN])) }}
        run: |
          Write-Host $ENV:SECRETS_JSON
          $secrets = $ENV:SECRETS_JSON | ConvertFrom-Json
          Write-Host $secrets.S1.Length
          Write-Host $secrets.S2.Length
          Write-Host $secrets.S3.Length
