name: Secrets

on:
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: GetSecret1
        id: getsecrets1
        env:
          SECRETS_JSON: '{"S1":"${{ secrets.S1 }}","S2":"${{ secrets.S2 }}","S3":"${{ secrets.S3 }}"}'
        run: |
          Write-Host $ENV:SECRETS_JSON
          $secrets = $ENV:SECRETS | ConvertFrom-Json
          Write-Host $secrets.S1.Length
          Write-Host $secrets.S2.Length
          Write-Host $secrets.S3.Length
